sudo: required
dist: trusty
language: node_js
node_js:
  - "8"

before_install:
  - npm install -g npm@5
script:
   - cd ./greeting-service
   - npm install -d
   - npm run ci
   - cd ..
   - cd cute-name-service
   - npm install -d
   - npm run ci
branches:
  only:
    - master
